"""Pure Baseline/Ratchet V1 contract and comparison foundation.

This package deliberately has no policy, Git, SARIF, CLI, or filesystem
integration. Consumers admit inputs and locate observations elsewhere, then use
these immutable models and the pure comparator.
"""

from modules.ratchet.comparison import (
    ComparisonDecision,
    ComparisonRecord,
    CurrentObservation,
    RatchetComparisonError,
    compare_observations,
)
from modules.ratchet.admission import (
    AdmittedBaselineArtifact,
    AdmittedBaselineSubjects,
    BaselineAdmissionError,
    BaselineArtifactOrigin,
    BaselineTrustContext,
    SourceRunEvidence,
    SourceCoordinateEvidence,
    SourceSubjectEvidence,
    admit_and_pair_baseline,
    admit_baseline,
    require_revision_compatibility,
)
from modules.ratchet.contract import (
    BASELINE_FORMAT,
    BASELINE_FORMAT_VERSION,
    BaselineObservation,
    CoordinateManifestEntry,
    CoordinateStatus,
    MetricContractBinding,
    PortableSubjectBinding,
    RatchetBaseline,
    RatchetContractError,
    RatchetDirection,
    RatchetRule,
    RatchetScope,
    RatchetSeverity,
    SourceRunBinding,
    canonical_bytes,
    canonical_metric_number,
    canonical_json,
    parse_baseline_json,
)
from modules.ratchet.pairing import (
    ContractCompatibilityError,
    CurrentSubject,
    SubjectPair,
    SubjectPairingError,
    pair_subjects,
    require_contract_compatibility,
)
from modules.ratchet.observations import (
    CurrentMetricObservation,
    MetricFamily,
    ObservationCompleteness,
    ObservationExtractionError,
    RatchetMetricDefinition,
    V1_METRICS,
    V1_METRICS_BY_ID,
    extract_current_observations,
    extract_persisted_observations,
    require_v1_metric,
)
from modules.ratchet.orchestration import (
    ComparisonOrchestrationError,
    ComparisonStatus,
    OrchestratedComparison,
    extract_and_compare,
    orchestrate_comparisons,
)
from modules.ratchet.check_service import (
    RatchetCheckEvaluation,
    RatchetCheckRequest,
    RatchetCheckServiceError,
    evaluate_ratchet_check,
    integrate_ratchet_check_result,
    not_configured_summary,
)
from modules.ratchet.semantics import (
    MeasurementSemantics,
    MeasurementSemanticsError,
    ProducerIdentity,
    SEMANTICS_FINGERPRINT_VERSION,
    SemanticsCompatibilityError,
    VersionBinding,
    producer_from_manifest,
    require_producer_compatibility,
    require_semantics_compatibility,
    semantics_from_manifest,
)
from modules.ratchet.capture import (
    BaselineCaptureError,
    CapturedBaseline,
    capture_baseline,
    source_run_evidence_from_run,
)

__all__ = [
    "AdmittedBaselineArtifact",
    "AdmittedBaselineSubjects",
    "BASELINE_FORMAT",
    "BASELINE_FORMAT_VERSION",
    "BaselineObservation",
    "BaselineCaptureError",
    "BaselineAdmissionError",
    "BaselineArtifactOrigin",
    "BaselineTrustContext",
    "ComparisonDecision",
    "CoordinateManifestEntry",
    "CoordinateStatus",
    "ComparisonOrchestrationError",
    "ComparisonRecord",
    "ComparisonStatus",
    "ContractCompatibilityError",
    "CurrentSubject",
    "CurrentObservation",
    "CurrentMetricObservation",
    "CapturedBaseline",
    "MetricFamily",
    "MetricContractBinding",
    "MeasurementSemantics",
    "MeasurementSemanticsError",
    "ObservationCompleteness",
    "ObservationExtractionError",
    "OrchestratedComparison",
    "PortableSubjectBinding",
    "ProducerIdentity",
    "RatchetBaseline",
    "RatchetComparisonError",
    "RatchetCheckEvaluation",
    "RatchetCheckRequest",
    "RatchetCheckServiceError",
    "RatchetContractError",
    "RatchetDirection",
    "RatchetMetricDefinition",
    "RatchetRule",
    "RatchetScope",
    "RatchetSeverity",
    "SourceRunBinding",
    "SourceRunEvidence",
    "SourceCoordinateEvidence",
    "SourceSubjectEvidence",
    "SubjectPair",
    "SubjectPairingError",
    "V1_METRICS",
    "V1_METRICS_BY_ID",
    "VersionBinding",
    "admit_and_pair_baseline",
    "admit_baseline",
    "canonical_bytes",
    "canonical_metric_number",
    "canonical_json",
    "compare_observations",
    "extract_and_compare",
    "extract_current_observations",
    "extract_persisted_observations",
    "capture_baseline",
    "evaluate_ratchet_check",
    "integrate_ratchet_check_result",
    "not_configured_summary",
    "orchestrate_comparisons",
    "pair_subjects",
    "parse_baseline_json",
    "require_contract_compatibility",
    "require_producer_compatibility",
    "require_semantics_compatibility",
    "require_revision_compatibility",
    "require_v1_metric",
    "producer_from_manifest",
    "semantics_from_manifest",
    "source_run_evidence_from_run",
    "SEMANTICS_FINGERPRINT_VERSION",
    "SemanticsCompatibilityError",
]
