"""Canonical single-pass repository inventory and centralized exclusions."""

from __future__ import annotations

import hashlib
import io
import json
import os
import re
import subprocess
import time
import tokenize
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Callable, Iterator

from modules.config import (
    AnalysisConfig,
    JAVASCRIPT_FAMILY_EXTENSIONS,
    SUPPORTED_EXTENSIONS,
    git_command_prefix,
)


CONFIG_EXTENSIONS = {
    ".cfg", ".conf", ".ini", ".json", ".properties", ".toml", ".xml", ".yaml", ".yml"
}
CONFIG_NAMES = {
    ".babelrc", ".flowconfig", "babel.config.cjs", "babel.config.js",
    "babel.config.mjs", "build.gradle", "build.gradle.kts", "cargo.toml",
    "craco.config.cjs", "craco.config.js", "go.mod", "go.sum",
    "gradle.properties", "makefile", "package.json", "pom.xml", "pyproject.toml",
    "requirements.txt", "setup.cfg", "setup.py", "tsconfig.json",
}
TEXT_CACHE_EXTENSIONS = set(SUPPORTED_EXTENSIONS) | CONFIG_EXTENSIONS | {
    ".cs", ".gradle", ".kt", ".kts", ".md", ".php", ".rb", ".sql", ".tf", ".txt"
}
INFRASTRUCTURE_NAMES = {
    "compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml",
    "dockerfile", "helmfile.yaml", "helmfile.yml", "terraform.tf",
}
GENERATED_MARKER = re.compile(
    rb"(?i)(code generated .* do not edit|auto[- ]generated|automatically generated|generated by\b)"
)
TEST_DIRECTORY_PATTERN = re.compile(r"^(?:tests?|specs?|fixtures?)(?:[_-].+)$")
TEST_RUNNER_CONFIG = re.compile(
    r"^(?:cypress|jest|playwright|vitest)\.config\.(?:[cm]?[jt]sx?|mts|cts)$|^karma\.conf\.(?:[cm]?js|ts)$"
)
GENERATED_HEADER_PREFIX_BYTES = 64 * 1024
CONTENT_CLASSIFICATION_PREFIX_BYTES = 64 * 1024
FREEMARKER_DIRECTIVE = re.compile(
    rb"(?m)^[ \t]*(?:<#[A-Za-z][A-Za-z0-9_]*\b|</#[A-Za-z][A-Za-z0-9_]*\s*>|"
    rb"<@[A-Za-z][A-Za-z0-9_.-]*\b|</@[A-Za-z][A-Za-z0-9_.-]*\s*>)"
)
MAKO_MODULE_DIRECTIVE = re.compile(rb"(?m)^[ \t]*<%![\s\S]{0,8192}?%>")
MAKO_BLOCK = re.compile(rb"(?m)^[ \t]*<%(?![!%])[\s\S]{0,4096}?%>")
GO_TEMPLATE_DIRECTIVE = re.compile(
    rb"(?m)^[ \t]*\{\{-?[ \t]*(?:if|range|with|define|block|template|else|end)\b"
)
BUILD_PLACEHOLDER = re.compile(rb"@[A-Za-z_][A-Za-z0-9_.-]*@")
JINJA_MARKER = re.compile(rb"(?:\{\{[^{}\r\n]+\}\}|\{%[^%\r\n]+%\}|\{#[^#\r\n]+#\})")
JSP_PAGE_DIRECTIVE = re.compile(rb"(?i)<%@\s*page\b[^%]{0,4096}%>")
JSP_TAG = re.compile(rb"(?i)</?jsp:[A-Za-z][A-Za-z0-9_.:-]*\b")
JSP_COMMENT = re.compile(rb"<%--[\s\S]{0,8192}?--%>")
SCRIPT_WRAPPER = re.compile(rb"(?i)<script(?:\s|>)[\s\S]{0,65536}?</script\s*>")
THYMELEAF_EXPRESSION = re.compile(
    rb"\[\[(?:\$\{|@\{)[^\]\r\n]{1,4096}\}\]\]"
)
FREEMARKER_I18N = re.compile(
    rb"\$\{\s*I18n\.getMessage\s*\([^}\r\n]{1,2048}\)\s*\}"
)


@dataclass(slots=True)
class FileRecord:
    relative_path: str
    filename: str
    extension: str
    detected_language: str | None
    size_bytes: int | None
    content_hash: str | None
    is_source: bool
    is_test: bool
    is_generated: bool
    is_vendor: bool
    is_dependency: bool
    is_build_output: bool
    is_declaration_only: bool
    is_minified_or_bundled: bool
    is_configuration: bool
    is_infrastructure: bool
    included_in_metrics: bool
    exclusion_reason: str | None
    read_status: str
    content_type: str | None = None
    template_family: str | None = None
    template_evidence_category: str | None = None
    template_evidence_summary: str | None = None
    git_mode: str | None = None
    is_git_symlink: bool = False
    is_git_submodule: bool = False
    git_symlink_target: str | None = None
    git_symlink_target_exists: bool | None = None
    line_ending_style: str | None = None
    byte_order_mark: str | None = None
    parser_normalization_applied: bool = False
    parser_compatibility_strategy: str | None = None
    parser_byte_offset_adjustment: int = 0
    oversized: bool = False
    read_error: str | None = None
    detected_encoding: str | None = None
    encoding_error: str | None = None
    original_encoding: str | None = None
    parser_encoding: str | None = None
    encoding_transformation_applied: str | None = None
    original_byte_length: int | None = None
    parser_byte_length: int | None = None
    parser_offsets_map_directly_to_original_bytes: bool = True
    original_byte_offsets_available: bool = True
    nul_count: int = 0
    nul_density: float = 0.0
    nul_positions: list[int] = field(default_factory=list)
    nul_contexts: list[str] = field(default_factory=list)
    alternating_nul_evidence: dict[str, object] = field(default_factory=dict)
    suspected_bomless_utf16: bool = False
    nul_classification: str | None = None
    typed_javascript_dialect_evidence: list[dict[str, str]] = field(
        default_factory=list
    )
    loc_status: str = "not_applicable"
    classes_structs_status: str = "not_applicable"
    methods_functions_status: str = "not_applicable"
    malformed_nodes: list[dict[str, object]] = field(default_factory=list)
    parse_status: str = "not_applicable"
    parse_error: str | None = None
    error_category: str | None = None
    parser_diagnostic: dict[str, object] | None = None
    _absolute_path: Path = field(default=Path(), repr=False)

    def to_dict(self) -> dict[str, object]:
        result = asdict(self)
        result.pop("_absolute_path", None)
        return result


def _language_and_declaration(path: Path) -> tuple[str | None, bool]:
    lower = path.name.lower()
    if lower.endswith((".d.ts", ".d.mts", ".d.cts")):
        return "TypeScript", True
    if lower.endswith(".pyi"):
        return "Python", True
    extension = path.suffix.lower()
    return SUPPORTED_EXTENSIONS.get(extension), False


def _test_path(relative: Path, policy: dict[str, object]) -> bool:
    lower_parts = {part.lower() for part in relative.parent.parts}
    name = relative.name.lower()
    stem = relative.stem.lower()
    if lower_parts & set(policy["test_directories"]) or lower_parts & {
        "storagetest", "testsupport", "testutil", "testutils",
    } or any(
        TEST_DIRECTORY_PATTERN.fullmatch(part) for part in lower_parts
    ):
        return True
    if TEST_RUNNER_CONFIG.fullmatch(name):
        return True
    if name in {"conftest.py", "test.py", "tests.py"} or name.endswith("_test.go"):
        return True
    if name.startswith("test_") or stem.endswith(
        ("_test", ".test", ".spec", ".unit", ".integration", ".e2e")
    ):
        return True
    if name.endswith(("test.java", "tests.java")):
        return True
    return False


def _domain_vendor_directory(relative: Path, language: str | None) -> bool:
    """Recognize application-domain ``vendors`` features, not third-party trees."""
    if language not in {"JavaScript", "TypeScript", "Python", "Java"}:
        return False
    parts = [part.lower() for part in relative.parent.parts]
    domain_containers = {
        "components", "domain", "domains", "entities", "features", "models", "pages", "routes", "views",
    }
    return any(
        part in {"vendor", "vendors"}
        and index > 0
        and parts[index - 1] in domain_containers
        and "src" in parts[:index]
        for index, part in enumerate(parts)
    )


def _domain_vendor_path(relative: Path) -> bool:
    parts = [part.lower() for part in relative.parts]
    if not parts or parts[-1] not in {"vendor", "vendors"}:
        return False
    domain_containers = {
        "components", "domain", "domains", "entities", "features", "models", "pages", "routes", "views",
    }
    return len(parts) > 1 and parts[-2] in domain_containers and "src" in parts[:-1]


def _pruned_directory_reason(relative: Path, policy: dict[str, object]) -> str | None:
    name = relative.name.lower()
    if name in {".git", ".hg", ".svn"}:
        return "vcs_metadata"
    if _domain_vendor_path(relative):
        return None
    if name in {"vendor", "vendors", "third-party", "third_party"}:
        return "vendor"
    if name in set(policy["dependency_directories"]):
        return "dependency"
    if name in set(policy["build_output_directories"]):
        return "build_output"
    if name in set(policy["cache_directories"]):
        return "cache"
    if name == "generated" or name.startswith("generated-"):
        return "generated"
    if name in set(policy["excluded_directories"]):
        return "excluded_directory"
    return None


def _directory_flags(
    relative: Path,
    policy: dict[str, object],
    language: str | None,
) -> tuple[bool, bool, bool, bool]:
    parts = {part.lower() for part in relative.parent.parts}
    domain_vendor = _domain_vendor_directory(relative, language)
    dependency_directories = set(policy["dependency_directories"])
    excluded_directories = set(policy["excluded_directories"])
    if domain_vendor:
        dependency_directories -= {"vendor", "vendors"}
        excluded_directories -= {"vendor", "vendors"}
    dependency = bool(
        parts & (dependency_directories | {".venv", "venv"})
        or parts & {"assets", "public", "resources", "static", "webapp", "wwwroot"}
        and parts & {"lib", "libs", "plugins", "vendor", "vendors"}
    )
    build = bool(parts & set(policy["build_output_directories"]))
    vendor = not domain_vendor and bool(parts & {"vendor", "vendors", "third-party", "third_party"})
    excluded = bool(parts & excluded_directories)
    return vendor, dependency, build, excluded


def _generated_name(path: Path, policy: dict[str, object]) -> bool:
    name = path.name.lower()
    parent_parts = {part.lower() for part in path.parent.parts}
    return (
        any(name.endswith(suffix) for suffix in policy["generated_suffixes"])
        or name.startswith("zz_generated.")
        or any(part == "generated" or part.startswith("generated-") for part in parent_parts)
        or "migrations" in parent_parts and path.suffix.lower() == ".py"
    )


def _minified_name(path: Path, policy: dict[str, object]) -> bool:
    name = path.name.lower()
    return any(name.endswith(suffix) for suffix in policy["minified_or_bundle_suffixes"])


def _generated_comment_header(content: bytes, language: str | None) -> bool:
    """Accept generated markers only in the initial language comment/header region."""
    if language not in {"Java", "JavaScript", "TypeScript", "Python", "Go"}:
        return False
    in_block = False
    for index, raw_line in enumerate(content.splitlines()[:20]):
        line = raw_line.lstrip()
        if index == 0 and line.startswith(b"\xef\xbb\xbf"):
            line = line[3:].lstrip()
        if not line:
            continue
        if index == 0 and line.startswith(b"#!"):
            continue
        comment = b""
        if language == "Python":
            if not line.startswith(b"#"):
                break
            comment = line[1:]
        elif in_block:
            comment = line
            if b"*/" in line:
                in_block = False
        elif line.startswith(b"//"):
            comment = line[2:]
        elif line.startswith(b"/*"):
            comment = line[2:]
            in_block = b"*/" not in line
        else:
            break
        if GENERATED_MARKER.search(comment):
            return True
    return False


def _without_bom_and_leading_space(content: bytes) -> bytes:
    candidate = content.lstrip(b" \t\r\n")
    if candidate.startswith(b"\xef\xbb\xbf"):
        candidate = candidate[3:].lstrip(b" \t\r\n")
    return candidate


def _line_ending_style(content: bytes) -> str:
    crlf = content.count(b"\r\n")
    lone_cr = content.count(b"\r") - crlf
    lone_lf = content.count(b"\n") - crlf
    present = sum(bool(value) for value in (crlf, lone_cr, lone_lf))
    if present == 0:
        return "none"
    if present > 1:
        return "mixed"
    if crlf:
        return "crlf"
    if lone_cr:
        return "cr"
    return "lf"


def _byte_order_mark(content: bytes) -> str | None:
    if content.startswith(b"\xef\xbb\xbf"):
        return "utf-8"
    if content.startswith(b"\xff\xfe"):
        return "utf-16-le"
    if content.startswith(b"\xfe\xff"):
        return "utf-16-be"
    return None


def _javascript_nul_contexts(content: bytes) -> list[str]:
    """Classify NUL positions with a deliberately small JS/TS lexical scanner."""
    contexts: list[str] = []
    state = "code"
    quote = 0
    escaped = False
    template_expression_depth = 0
    index = 0
    while index < len(content):
        byte = content[index]
        following = content[index + 1] if index + 1 < len(content) else None
        if state in {"single", "double"}:
            if byte == 0:
                contexts.append("quoted_string")
            if escaped:
                escaped = False
            elif byte == 92:
                escaped = True
            elif byte == quote:
                state = "code"
        elif state == "template":
            if byte == 0:
                contexts.append("template_literal")
            if escaped:
                escaped = False
            elif byte == 92:
                escaped = True
            elif byte == 96:
                state = "code"
            elif byte == 36 and following == 123:
                template_expression_depth = 1
                state = "code"
                index += 1
        elif state == "line_comment":
            if byte == 0:
                contexts.append("comment")
            if byte in {10, 13}:
                state = "code"
        elif state == "block_comment":
            if byte == 0:
                contexts.append("comment")
            if byte == 42 and following == 47:
                state = "code"
                index += 1
        else:
            if byte == 0:
                contexts.append("unrecognized")
            elif byte == 47 and following == 47:
                state = "line_comment"
                index += 1
            elif byte == 47 and following == 42:
                state = "block_comment"
                index += 1
            elif byte in {34, 39}:
                quote = byte
                escaped = False
                state = "double" if byte == 34 else "single"
            elif byte == 96:
                escaped = False
                state = "template"
            elif template_expression_depth:
                if byte == 123:
                    template_expression_depth += 1
                elif byte == 125:
                    template_expression_depth -= 1
                    if template_expression_depth == 0:
                        state = "template"
        index += 1
    return contexts


def _nul_statistics(content: bytes) -> dict[str, object]:
    positions = [index for index, byte in enumerate(content) if byte == 0]
    count = len(positions)
    even = sum(position % 2 == 0 for position in positions)
    odd = count - even
    parity_purity = max(even, odd) / count if count else 0.0
    evidence = {
        "even_position_nuls": even,
        "odd_position_nuls": odd,
        "dominant_parity_ratio": round(parity_purity, 6),
        "alternating": bool(count >= 4 and parity_purity >= 0.75),
    }
    return {
        "nul_count": count,
        "nul_density": count / len(content) if content else 0.0,
        "nul_positions": positions,
        "alternating_nul_evidence": evidence,
    }


def _classify_non_bom_source(
    content: bytes,
    language: str | None,
) -> tuple[str | None, list[str], bool, str | None]:
    """Strictly decode before distinguishing textual NUL from binary evidence."""
    try:
        decoded = content.decode("utf-8", errors="strict")
    except UnicodeDecodeError as exc:
        return "invalid_utf8", [], False, f"Invalid UTF-8 source: {exc}"

    statistics = _nul_statistics(content)
    nul_count = int(statistics["nul_count"])
    non_nul = [byte for byte in content if byte]
    printable = sum(byte in {9, 10, 13} or 32 <= byte <= 126 for byte in non_nul)
    printable_ratio = printable / len(non_nul) if non_nul else 0.0
    binary_controls = sum(
        byte < 32 and byte not in {0, 9, 10, 13} for byte in content
    )
    binary_control_density = binary_controls / len(content) if content else 0.0
    if binary_control_density > 0.10:
        return (
            "arbitrary_binary",
            [],
            False,
            "Arbitrary binary control-byte density in source candidate",
        )
    if not nul_count:
        return None, [], False, None

    evidence = statistics["alternating_nul_evidence"]
    suspected_utf16 = bool(
        evidence["alternating"]
        and float(statistics["nul_density"]) >= 0.20
        and printable_ratio >= 0.85
        and any(character.isalnum() for character in decoded.replace("\x00", ""))
    )
    if suspected_utf16:
        return (
            "bomless_utf16_like",
            [],
            True,
            "BOM-less UTF-16-like alternating NUL source is unsupported",
        )
    if float(statistics["nul_density"]) > 0.10:
        return (
            "high_density_alternating_nul",
            [],
            False,
            "High-density NUL source is not accepted as ordinary UTF-8",
        )

    contexts = (
        _javascript_nul_contexts(content)
        if language in {"JavaScript", "TypeScript"}
        else ["unrecognized"] * nul_count
    )
    permitted = {"quoted_string", "template_literal", "comment"}
    if len(contexts) == nul_count and all(context in permitted for context in contexts):
        return "low_density_intentional_textual_nul", contexts, False, None
    return (
        "untrusted_textual_nul",
        contexts,
        False,
        "NUL byte outside a recognized quoted string, template literal, or comment",
    )


def _qt_translation_catalog(content: bytes) -> bool:
    """Recognize a Qt Linguist XML catalog from a bounded `.ts` prefix."""
    candidate = _without_bom_and_leading_space(
        content[:CONTENT_CLASSIFICATION_PREFIX_BYTES]
    )
    declaration = re.match(rb"<\?xml(?:\s|\?>)[\s\S]{0,1024}?\?>", candidate)
    has_qt_doctype = bool(
        declaration
        and re.search(rb"<!DOCTYPE[ \t\r\n]+TS(?:[ \t\r\n>])", candidate[:4096])
    )
    if has_qt_doctype:
        return True
    if declaration:
        candidate = candidate[declaration.end() :].lstrip(b" \t\r\n")
    doctype = re.match(rb"<!DOCTYPE[ \t\r\n]+TS(?:[ \t\r\n][^>]{0,2048})?>", candidate)
    if doctype:
        candidate = candidate[doctype.end() :].lstrip(b" \t\r\n")
    return bool(re.match(rb"<TS(?=[ \t\r\n>/])", candidate))


def _template_evidence(
    content: bytes,
    relative: Path,
    language: str | None,
) -> tuple[str | None, str | None, str | None]:
    """Return only high-confidence, dialect-specific mixed-template evidence."""
    prefix = content[:CONTENT_CLASSIFICATION_PREFIX_BYTES]
    script_language = language in {"JavaScript", "TypeScript"}
    if script_language and (JSP_PAGE_DIRECTIVE.search(prefix) or JSP_TAG.search(prefix)):
        return "JSP", "jsp_directive", "JSP page/tag directive in bounded source prefix"
    if script_language and JSP_COMMENT.search(prefix) and SCRIPT_WRAPPER.search(prefix):
        return "JSP", "jsp_comment_with_script", "JSP comment plus script wrapper"
    if script_language and THYMELEAF_EXPRESSION.search(prefix):
        return "Thymeleaf", "thymeleaf_inline_expression", "Thymeleaf inline expression"
    if script_language and FREEMARKER_DIRECTIVE.search(prefix):
        return "Freemarker", "freemarker_directive", "Freemarker directive"
    template_parts = {part.lower() for part in relative.parent.parts}
    if (
        script_language
        and template_parts & {"template", "templates"}
        and FREEMARKER_I18N.search(prefix)
    ):
        return (
            "Freemarker",
            "freemarker_substitution_with_template_path",
            "Freemarker substitution corroborated by template path",
        )
    if script_language and (
        MAKO_MODULE_DIRECTIVE.search(prefix) or len(MAKO_BLOCK.findall(prefix)) >= 2
    ):
        return "Mako", "mako_directive", "Mako directive evidence"
    if language == "Go" and len(GO_TEMPLATE_DIRECTIVE.findall(prefix)) >= 2:
        return "Go template", "go_template_directives", "Multiple Go-template directives"
    placeholders = set(BUILD_PLACEHOLDER.findall(prefix))
    if language == "Java" and len(placeholders) >= 2:
        return "build placeholder", "multiple_build_placeholders", "Multiple build placeholders"
    if (
        language in {"JavaScript", "TypeScript"}
        and "templates" in template_parts
        and JINJA_MARKER.search(prefix)
    ):
        return "Jinja", "jinja_marker_with_template_path", "Jinja marker in template path"
    return None, None, None


def _html_script_document(content: bytes, language: str | None) -> bool:
    if language not in {"JavaScript", "TypeScript"}:
        return False
    candidate = _without_bom_and_leading_space(
        content[:CONTENT_CLASSIFICATION_PREFIX_BYTES]
    )
    return bool(
        re.match(rb"(?i)(?:<!doctype\s+html[^>]*>\s*|<html(?:\s|>)[\s\S]{0,4096}?)?<script(?:\s|>)", candidate)
        and re.search(rb"(?i)</script\s*>", candidate)
    )


class RepositoryInventory:
    """A deterministic inventory built by exactly one ``os.walk`` call."""

    def __init__(
        self,
        root: str | Path,
        config: AnalysisConfig | None = None,
        *,
        full_inventory: bool = True,
        progress: Callable[[dict[str, int]], None] | None = None,
        git_entries: dict[str, tuple[str, str]] | None = None,
        native_links: dict[str, str | None] | None = None,
    ):
        self.root = Path(root).resolve()
        self.config = config or AnalysisConfig.from_env()
        self.full_inventory = full_inventory
        self._progress = progress
        self._native_links = native_links or {}
        self.records: list[FileRecord] = []
        self._by_relative: dict[str, FileRecord] = {}
        self._by_name: dict[str, list[FileRecord]] = defaultdict(list)
        self._content_cache: dict[str, bytes] = {}
        self._decoded_text_cache: dict[tuple[str, str], str] = {}
        self.decode_operations = 0
        self.file_content_reads = 0
        self.bytes_read = 0
        self.files_hashed = 0
        self.cache_reuses = 0
        self.content_cache_reuses = 0
        self.text_cache_reuses = 0
        self.parser_invocations = 0
        self.javascript_dialect_evidence: list[dict[str, str]] = []
        self.directories_seen = 0
        self.files_seen = 0
        self.source_candidates = 0
        self.unsupported_files_observed = 0
        self.generated_prefix_reads = 0
        self.walk_count = 0
        self.inventory_status = "complete"
        self.directory_errors: list[dict[str, object]] = []
        self.pruned_directories: list[dict[str, object]] = []
        self.nested_repositories: list[str] = []
        self.excluded_directories: Counter[str] = Counter()
        self.git_mode_command_count = 0
        self.git_mode_map_status = "failed"
        self.git_mode_map_reason: str | None = None
        self.git_mode_map_available = False
        self.git_mode_map_error: str | None = None
        self.git_mode_entry_count = 0
        self.git_mode_command_duration_seconds = 0.0
        self.git_mode_effective_timeout_seconds = float(
            self.config.git_timeout_seconds
        )
        self._git_entries: dict[str, tuple[str, str]] = {}
        if not self.root.is_dir():
            raise FileNotFoundError(f"Repository path does not exist: {self.root}")
        if git_entries is None:
            self._git_entries = self._load_git_entries()
        else:
            self._git_entries = dict(git_entries)
            self.git_mode_map_status = "available"
            self.git_mode_map_available = True
            self.git_mode_entry_count = len(git_entries)
        self._build()

    def _load_git_entries(self) -> dict[str, tuple[str, str]]:
        """Load every tracked mode once and preserve the command result state."""
        self.git_mode_command_count += 1
        started = time.perf_counter()
        command = [
            *git_command_prefix(),
            "-C",
            str(self.root),
            "ls-files",
            "-s",
            "-z",
        ]
        try:
            result = subprocess.run(
                command,
                check=True,
                capture_output=True,
                timeout=self.git_mode_effective_timeout_seconds,
            )
        except subprocess.TimeoutExpired as exc:
            self.git_mode_map_status = "timed_out"
            self.git_mode_map_error = (
                f"Git mode map command timed out after "
                f"{self.git_mode_effective_timeout_seconds:g}s"
            )
            if exc.stderr:
                detail = (
                    exc.stderr.decode("utf-8", errors="replace")
                    if isinstance(exc.stderr, bytes)
                    else str(exc.stderr)
                ).strip()
                if detail:
                    self.git_mode_map_error += f": {detail[:500]}"
            self.inventory_status = "partial"
            return {}
        except subprocess.CalledProcessError as exc:
            raw_detail = exc.stderr or exc.stdout or str(exc)
            detail = (
                raw_detail.decode("utf-8", errors="replace")
                if isinstance(raw_detail, bytes)
                else str(raw_detail)
            ).strip()
            if "not a git repository" in detail.casefold():
                # Artifact 1.7 normalizes state and cause. 1.5/1.6 wrote the
                # compound `unavailable_not_git`, which encoded both in one
                # string; readers normalize that historical value rather than
                # the artifacts being rewritten.
                self.git_mode_map_status = "unavailable"
                self.git_mode_map_reason = "not_git_repository"
            else:
                self.git_mode_map_status = "failed"
                self.inventory_status = "partial"
            self.git_mode_map_error = detail[:500] or (
                f"Git mode map command exited {exc.returncode}"
            )
            return {}
        except OSError as exc:
            self.git_mode_map_status = "failed"
            self.git_mode_map_error = f"{type(exc).__name__}: {exc}"
            self.inventory_status = "partial"
            return {}
        finally:
            self.git_mode_command_duration_seconds = round(
                time.perf_counter() - started, 6
            )
        entries: dict[str, tuple[str, str]] = {}
        for raw in result.stdout.split(b"\0"):
            if not raw or b"\t" not in raw:
                continue
            metadata, raw_path = raw.split(b"\t", 1)
            fields = metadata.decode("ascii", errors="replace").split()
            if len(fields) < 2:
                continue
            path = raw_path.decode("utf-8", errors="surrogateescape").replace("\\", "/")
            entries[path] = (fields[0], fields[1])
        self.git_mode_map_status = "available"
        self.git_mode_map_available = True
        self.git_mode_map_error = None
        self.git_mode_entry_count = len(entries)
        return entries

    def _git_symlink_details(
        self, path: Path
    ) -> tuple[str | None, bool | None, bytes | None]:
        try:
            if path.is_symlink():
                target = os.readlink(path)
                raw = os.fsencode(target)
            else:
                with path.open("rb") as handle:
                    raw = handle.read(4097)
                if len(raw) > 4096:
                    return None, None, None
                target = raw.decode("utf-8")
        except (OSError, UnicodeError):
            return None, None, None
        target = target.rstrip("\r\n")
        if not target or "\x00" in target:
            return None, None, None
        candidate = Path(target)
        if candidate.is_absolute():
            return target, False, raw
        try:
            resolved = (path.parent / candidate).resolve(strict=False)
            resolved.relative_to(self.root)
        except (OSError, ValueError):
            exists_inside = False
        else:
            exists_inside = resolved.exists()
        return target, exists_inside, raw

    def _read_and_hash(self, path: Path) -> tuple[str | None, str, bytes | None, str | None]:
        digest = hashlib.sha256()
        cached = bytearray()
        self.file_content_reads += 1
        try:
            with path.open("rb") as handle:
                for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                    self.bytes_read += len(chunk)
                    digest.update(chunk)
                    cached.extend(chunk)
        except OSError as exc:
            return None, "failed", None, f"{type(exc).__name__}: {exc}"
        self.files_hashed += 1
        return digest.hexdigest(), "complete", bytes(cached), None

    def _collect_javascript_dialect_configuration(
        self,
        path: Path,
        relative: Path,
        content: bytes | None = None,
    ) -> None:
        """Collect bounded, explicit repository evidence for typed JavaScript."""
        name = relative.name.lower()
        if name not in CONFIG_NAMES:
            return
        if name == ".flowconfig":
            candidates = [
                {
                    "configuration_path": relative.as_posix(),
                    "evidence_type": "flow_configuration",
                    "signal": ".flowconfig",
                }
            ]
        else:
            if content is None:
                self.file_content_reads += 1
                try:
                    with path.open("rb") as handle:
                        content = handle.read(1024 * 1024 + 1)
                except OSError:
                    return
                self.bytes_read += len(content)
            if len(content) > 1024 * 1024:
                return
            candidates: list[dict[str, str]] = []
            if name == "package.json":
                try:
                    package = json.loads(content.decode("utf-8", errors="strict"))
                except (UnicodeError, json.JSONDecodeError):
                    return
                dependencies: dict[str, object] = {}
                if isinstance(package, dict):
                    for field_name in (
                        "dependencies",
                        "devDependencies",
                        "optionalDependencies",
                        "peerDependencies",
                    ):
                        values = package.get(field_name)
                        if isinstance(values, dict):
                            dependencies.update(values)
                strong_signals = {
                    "@babel/preset-flow",
                    "babel-eslint",
                    "babel-preset-flow",
                    "flow-bin",
                    "flow-remove-types",
                }
                for signal in sorted(strong_signals & set(dependencies)):
                    candidates.append(
                        {
                            "configuration_path": relative.as_posix(),
                            "evidence_type": "package_dependency",
                            "signal": signal,
                        }
                    )
            elif name.startswith("babel.config") or name == ".babelrc":
                text = content.decode("utf-8", errors="ignore")
                for signal in ("@babel/preset-flow", "preset-flow"):
                    if signal in text:
                        candidates.append(
                            {
                                "configuration_path": relative.as_posix(),
                                "evidence_type": "babel_flow_configuration",
                                "signal": signal,
                            }
                        )
        known = {
            (item["configuration_path"], item["evidence_type"], item["signal"])
            for item in self.javascript_dialect_evidence
        }
        for candidate in candidates:
            key = (
                candidate["configuration_path"],
                candidate["evidence_type"],
                candidate["signal"],
            )
            if key not in known:
                self.javascript_dialect_evidence.append(candidate)
                known.add(key)

    def _read_source_candidate(
        self,
        path: Path,
        relative: Path,
        language: str | None,
        size: int,
    ) -> tuple[
        str | None,
        str,
        bytes | None,
        str | None,
        bool,
        bool,
        str | None,
        str | None,
        str | None,
        str | None,
    ]:
        """Read an includable source once, stopping after a bounded exclusion prefix."""
        digest = hashlib.sha256()
        cached = bytearray()
        self.file_content_reads += 1
        self.generated_prefix_reads += 1
        try:
            with path.open("rb") as handle:
                prefix = handle.read(GENERATED_HEADER_PREFIX_BYTES)
                self.bytes_read += len(prefix)
                generated = _generated_comment_header(prefix, language)
                content_type = (
                    "qt_translation_catalog"
                    if relative.suffix.lower() == ".ts" and _qt_translation_catalog(prefix)
                    else None
                )
                if _html_script_document(prefix, language):
                    content_type = "html_script_document"
                (
                    template_family,
                    template_evidence_category,
                    template_evidence_summary,
                ) = _template_evidence(prefix, relative, language)
                if generated or content_type or template_family:
                    return (
                        None,
                        "prefix_only_excluded",
                        None,
                        None,
                        generated,
                        False,
                        content_type,
                        template_family,
                        template_evidence_category,
                        template_evidence_summary,
                    )
                digest.update(prefix)
                cached.extend(prefix)
                for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                    self.bytes_read += len(chunk)
                    digest.update(chunk)
                    cached.extend(chunk)
        except OSError as exc:
            return (
                None,
                "failed",
                None,
                f"{type(exc).__name__}: {exc}",
                False,
                False,
                None,
                None,
                None,
                None,
            )
        content = bytes(cached)
        newline_count = max(content.count(b"\n"), 1)
        minified = bool(
            language in {"JavaScript", "TypeScript"}
            and size > 20_000
            and size / newline_count > 500
        )
        self.files_hashed += 1
        return (
            digest.hexdigest(), "complete", content, None, False, minified,
            None, None, None, None,
        )

    def _classify_oversized_source_prefix(
        self,
        path: Path,
        relative: Path,
        language: str | None,
    ) -> tuple[
        str, str | None, bool, str | None, str | None, str | None, str | None
    ]:
        """Read only the bounded exclusion prefix of an oversized source."""
        self.file_content_reads += 1
        self.generated_prefix_reads += 1
        try:
            with path.open("rb") as handle:
                prefix = handle.read(GENERATED_HEADER_PREFIX_BYTES)
                self.bytes_read += len(prefix)
        except OSError as exc:
            return (
                "failed", f"{type(exc).__name__}: {exc}", False,
                None, None, None, None,
            )
        generated = _generated_comment_header(prefix, language)
        content_type = (
            "qt_translation_catalog"
            if relative.suffix.lower() == ".ts" and _qt_translation_catalog(prefix)
            else None
        )
        if _html_script_document(prefix, language):
            content_type = "html_script_document"
        (
            template_family,
            template_evidence_category,
            template_evidence_summary,
        ) = _template_evidence(prefix, relative, language)
        excluded = bool(generated or content_type or template_family)
        return (
            "prefix_only_excluded" if excluded else "skipped_oversized",
            None,
            generated,
            content_type,
            template_family,
            template_evidence_category,
            template_evidence_summary,
        )

    def _build_record(
        self,
        path: Path,
        relative: Path,
        symlink: bool = False,
        git_mode: str | None = None,
    ) -> FileRecord | None:
        policy = self.config.exclusion_policy
        language, declaration = _language_and_declaration(relative)
        is_source = language is not None
        is_test = _test_path(relative, policy)
        vendor, dependency, build, excluded_directory = _directory_flags(relative, policy, language)
        generated = _generated_name(relative, policy)
        minified = _minified_name(relative, policy)
        name_lower = relative.name.lower()
        configuration = relative.suffix.lower() in CONFIG_EXTENSIONS or name_lower in CONFIG_NAMES
        infrastructure = (
            name_lower in INFRASTRUCTURE_NAMES
            or name_lower.startswith("dockerfile.")
            or relative.suffix.lower() == ".tf"
            or any(part.lower() in {"helm", "k8s", "kubernetes"} for part in relative.parts)
        )

        if is_source:
            self.source_candidates += 1
        elif not self.full_inventory and not symlink and git_mode not in {"120000", "160000"}:
            self.unsupported_files_observed += 1
            if (
                configuration
                and not symlink
                and git_mode not in {"120000", "160000"}
            ):
                self._collect_javascript_dialect_configuration(path, relative)
            return None

        size: int | None = None
        content_hash: str | None = None
        content: bytes | None = None
        read_error: str | None = None
        oversized = False
        detected_encoding: str | None = None
        encoding_error: str | None = None
        original_encoding: str | None = None
        parser_encoding: str | None = None
        encoding_transformation_applied: str | None = None
        original_byte_length: int | None = None
        parser_byte_length: int | None = None
        parser_offsets_map_directly_to_original_bytes = True
        original_byte_offsets_available = True
        nul_count = 0
        nul_density = 0.0
        nul_positions: list[int] = []
        nul_contexts: list[str] = []
        alternating_nul_evidence: dict[str, object] = {}
        suspected_bomless_utf16 = False
        nul_classification: str | None = None
        content_type: str | None = None
        template_family: str | None = None
        template_evidence_category: str | None = None
        template_evidence_summary: str | None = None
        line_ending_style: str | None = None
        byte_order_mark: str | None = None
        is_git_symlink = git_mode == "120000"
        is_git_submodule = git_mode == "160000"
        git_symlink_target: str | None = None
        git_symlink_target_exists: bool | None = None
        if is_git_submodule:
            read_status = "git_submodule_skipped"
        elif is_git_symlink:
            (
                git_symlink_target,
                git_symlink_target_exists,
                symlink_bytes,
            ) = self._git_symlink_details(path)
            read_status = "git_symlink_skipped"
            if symlink_bytes is not None:
                size = len(symlink_bytes)
                content_hash = hashlib.sha256(symlink_bytes).hexdigest()
        elif symlink:
            read_status = "symlink_skipped"
        else:
            try:
                size = path.stat().st_size
            except OSError as exc:
                read_status = "failed"
                read_error = f"{type(exc).__name__}: {exc}"
            else:
                path_exclusion = next(
                    (
                        reason
                        for condition, reason in (
                            (declaration, "declaration_only"),
                            (is_test, "test"),
                            (vendor, "vendor"),
                            (dependency, "dependency"),
                            (build, "build_output"),
                            (generated, "generated"),
                            (minified, "minified_or_bundled"),
                            (excluded_directory, "excluded_directory"),
                        )
                        if condition
                    ),
                    None,
                )
                should_read = bool(
                    is_source
                    or configuration
                    or infrastructure
                    or relative.suffix.lower() in TEXT_CACHE_EXTENSIONS
                )
                oversized = bool(
                    is_source and size > self.config.max_source_file_size_bytes
                )
                if oversized:
                    if is_source and path_exclusion is None:
                        (
                            read_status,
                            read_error,
                            generated_from_prefix,
                            content_type,
                            template_family,
                            template_evidence_category,
                            template_evidence_summary,
                        ) = (
                            self._classify_oversized_source_prefix(
                                path, relative, language
                            )
                        )
                        generated = generated or generated_from_prefix
                    else:
                        read_status = "skipped_oversized"
                elif not self.full_inventory and path_exclusion is not None:
                    read_status = "not_read_excluded"
                elif not self.full_inventory and is_source:
                    (
                        content_hash,
                        read_status,
                        content,
                        read_error,
                        generated_from_prefix,
                        minified_from_content,
                        content_type,
                        template_family,
                        template_evidence_category,
                        template_evidence_summary,
                    ) = self._read_source_candidate(path, relative, language, size)
                    generated = generated or generated_from_prefix
                    minified = minified or minified_from_content
                elif should_read:
                    content_hash, read_status, content, read_error = self._read_and_hash(path)
                else:
                    read_status = "not_read_unneeded"
                if content is not None and is_source:
                    if self.full_inventory:
                        generated = generated or _generated_comment_header(content, language)
                        content_type = (
                            "qt_translation_catalog"
                            if relative.suffix.lower() == ".ts"
                            and _qt_translation_catalog(content)
                            else None
                        )
                        if _html_script_document(content, language):
                            content_type = "html_script_document"
                        (
                            template_family,
                            template_evidence_category,
                            template_evidence_summary,
                        ) = _template_evidence(content, relative, language)
                        if language in {"JavaScript", "TypeScript"} and not minified:
                            newline_count = max(content.count(b"\n"), 1)
                            minified = size > 20_000 and size / newline_count > 500
                    byte_order_mark = _byte_order_mark(content)
                    original_byte_length = len(content)
                    nul_statistics = _nul_statistics(content)
                    nul_count = int(nul_statistics["nul_count"])
                    nul_density = float(nul_statistics["nul_density"])
                    nul_positions = list(nul_statistics["nul_positions"])
                    alternating_nul_evidence = dict(
                        nul_statistics["alternating_nul_evidence"]
                    )
                    if byte_order_mark in {"utf-16-le", "utf-16-be"}:
                        try:
                            decoded_utf16 = content.decode("utf-16", errors="strict")
                        except UnicodeDecodeError as exc:
                            encoding_error = f"{type(exc).__name__}: {exc}"
                            parser_byte_length = None
                        else:
                            parser_view = decoded_utf16.encode("utf-8")
                            detected_encoding = "utf-16"
                            parser_byte_length = len(parser_view)
                            line_ending_style = _line_ending_style(parser_view)
                        original_encoding = byte_order_mark
                        parser_encoding = "utf-8"
                        encoding_transformation_applied = "utf16_to_utf8"
                        parser_offsets_map_directly_to_original_bytes = False
                        original_byte_offsets_available = False
                        nul_classification = (
                            "bom_identified_utf16" if nul_count else None
                        )
                    else:
                        line_ending_style = _line_ending_style(content)
                        parser_byte_length = len(content)
                        if byte_order_mark == "utf-8":
                            original_encoding = "utf-8-sig"
                            if language == "Python":
                                detected_encoding = "utf-8-sig"
                            parser_encoding = "utf-8"
                            encoding_transformation_applied = "utf8_bom_removed"
                            parser_byte_length = max(0, len(content) - 3)
                            parser_offsets_map_directly_to_original_bytes = False
                        elif language == "Python":
                            try:
                                detected_encoding, _ = tokenize.detect_encoding(
                                    io.BytesIO(content).readline
                                )
                                original_encoding = detected_encoding
                                parser_encoding = "utf-8"
                                decoded_python = content.decode(
                                    detected_encoding, errors="strict"
                                )
                                parser_byte_length = len(
                                    decoded_python.encode("utf-8")
                                )
                                if detected_encoding.casefold().replace("_", "-") not in {
                                    "utf-8",
                                    "utf8",
                                }:
                                    encoding_transformation_applied = (
                                        "source_encoding_to_unicode_utf8"
                                    )
                                    parser_offsets_map_directly_to_original_bytes = False
                                    original_byte_offsets_available = False
                            except (LookupError, SyntaxError, UnicodeError) as exc:
                                encoding_error = f"{type(exc).__name__}: {exc}"
                        else:
                            (
                                nul_classification,
                                nul_contexts,
                                suspected_bomless_utf16,
                                strict_error,
                            ) = _classify_non_bom_source(content, language)
                            if strict_error:
                                original_encoding = "unknown"
                                parser_encoding = "raw-bytes"
                                encoding_error = strict_error
                            else:
                                original_encoding = "utf-8"
                                parser_encoding = "utf-8"
                        if language == "Python" and b"\x00" in content:
                            nul_classification = "untrusted_textual_nul"
                            nul_contexts = ["unrecognized"] * nul_count
                            encoding_error = (
                                "NUL byte found without a UTF-16 byte-order mark"
                            )
                if content is not None and configuration:
                    self._collect_javascript_dialect_configuration(
                        path, relative, content
                    )

        if content_type == "qt_translation_catalog":
            language = None
            is_source = False
        exclusion_reason = None
        for condition, reason in (
            (is_git_symlink, "git_symlink"),
            (is_git_submodule, "git_submodule"),
            (symlink, "symlink"),
            (declaration, "declaration_only"),
            (is_test, "test"),
            (vendor, "vendor"),
            (dependency, "dependency"),
            (build, "build_output"),
            (generated, "generated"),
            (minified, "minified_or_bundled"),
            (excluded_directory, "excluded_directory"),
            (content_type is not None, "content_type_mismatch"),
            (template_family is not None, "templated_source"),
        ):
            if condition:
                exclusion_reason = reason
                break
        included = is_source and exclusion_reason is None
        record = FileRecord(
            relative_path=relative.as_posix(),
            filename=relative.name,
            extension=relative.suffix.lower(),
            detected_language=language,
            size_bytes=size,
            content_hash=content_hash,
            is_source=is_source,
            is_test=is_test,
            is_generated=generated,
            is_vendor=vendor,
            is_dependency=dependency,
            is_build_output=build,
            is_declaration_only=declaration,
            is_minified_or_bundled=minified,
            is_configuration=configuration,
            is_infrastructure=infrastructure,
            included_in_metrics=included,
            exclusion_reason=exclusion_reason,
            read_status=read_status,
            content_type=content_type,
            template_family=template_family,
            template_evidence_category=template_evidence_category,
            template_evidence_summary=(
                template_evidence_summary
                or (
                    "HTML document/script wrapper in bounded source prefix"
                    if content_type == "html_script_document"
                    else None
                )
            ),
            git_mode=git_mode,
            is_git_symlink=is_git_symlink,
            is_git_submodule=is_git_submodule,
            git_symlink_target=git_symlink_target,
            git_symlink_target_exists=git_symlink_target_exists,
            line_ending_style=line_ending_style,
            byte_order_mark=byte_order_mark,
            oversized=oversized,
            read_error=read_error,
            detected_encoding=detected_encoding,
            encoding_error=encoding_error,
            original_encoding=original_encoding,
            parser_encoding=parser_encoding,
            encoding_transformation_applied=encoding_transformation_applied,
            original_byte_length=original_byte_length,
            parser_byte_length=parser_byte_length,
            parser_offsets_map_directly_to_original_bytes=(
                parser_offsets_map_directly_to_original_bytes
            ),
            original_byte_offsets_available=original_byte_offsets_available,
            nul_count=nul_count,
            nul_density=nul_density,
            nul_positions=nul_positions,
            nul_contexts=nul_contexts,
            alternating_nul_evidence=alternating_nul_evidence,
            suspected_bomless_utf16=suspected_bomless_utf16,
            nul_classification=nul_classification,
            _absolute_path=path,
        )
        if content is not None and (
            is_source
            or configuration
            or infrastructure
            or relative.suffix.lower() in TEXT_CACHE_EXTENSIONS
        ):
            if self.full_inventory or record.included_in_metrics:
                self._content_cache[record.relative_path] = content
        return record

    def _build(self) -> None:
        self.walk_count += 1
        roots_visited = 0

        def onerror(exc: OSError) -> None:
            filename = Path(exc.filename) if exc.filename else self.root
            try:
                relative = filename.resolve().relative_to(self.root).as_posix()
            except (OSError, ValueError):
                relative = filename.as_posix()
            self.directory_errors.append(
                {
                    "relative_path": relative or ".",
                    "exception_type": type(exc).__name__,
                    "errno": exc.errno,
                    "message": str(exc),
                }
            )
            self.inventory_status = "partial"

        for root, dirs, files in os.walk(
            self.root, topdown=True, onerror=onerror, followlinks=False
        ):
            roots_visited += 1
            self.directories_seen += 1
            root_path = Path(root)
            relative_root = root_path.relative_to(self.root)
            kept_dirs: list[str] = []
            for name in sorted(dirs, key=str.lower):
                candidate = root_path / name
                relative = candidate.relative_to(self.root)
                git_mode = self._git_entries.get(relative.as_posix(), (None, None))[0]
                is_link = candidate.is_symlink() or relative.as_posix() in self._native_links
                if is_link or git_mode in {"120000", "160000"}:
                    self.files_seen += 1
                    record = self._build_record(
                        candidate,
                        relative,
                        symlink=is_link,
                        git_mode=git_mode,
                    )
                    if record is not None:
                        self.records.append(record)
                    self.excluded_directories[
                        "git_submodule"
                        if git_mode == "160000"
                        else "git_symlink" if git_mode == "120000" else "symlink"
                    ] += 1
                    continue
                if (candidate / ".git").exists() or (candidate / ".hg").exists():
                    self.nested_repositories.append(relative.as_posix())
                    self.excluded_directories["nested_repository"] += 1
                    continue
                reason = _pruned_directory_reason(relative, self.config.exclusion_policy)
                if reason:
                    self.excluded_directories[reason] += 1
                    self.pruned_directories.append(
                        {
                            "path": relative.as_posix(),
                            "exclusion_reason": reason,
                            "descended": False,
                        }
                    )
                    continue
                kept_dirs.append(name)
            dirs[:] = kept_dirs
            for name in sorted(files, key=str.lower):
                self.files_seen += 1
                if name == ".git" and relative_root == Path("."):
                    self.excluded_directories["vcs_metadata"] += 1
                    continue
                path = root_path / name
                relative = path.relative_to(self.root)
                git_mode = self._git_entries.get(relative.as_posix(), (None, None))[0]
                record = self._build_record(
                    path,
                    relative,
                    symlink=path.is_symlink() or relative.as_posix() in self._native_links,
                    git_mode=git_mode,
                )
                if record is not None:
                    self.records.append(record)
                if self._progress and (
                    self.files_seen == 1 or self.files_seen % 500 == 0
                ):
                    self._progress(self.performance_counters())
        if self.directory_errors and roots_visited == 0:
            self.inventory_status = "failed"
        self.records.sort(key=lambda item: (item.relative_path.casefold(), item.relative_path))
        dialect_evidence = sorted(
            self.javascript_dialect_evidence,
            key=lambda item: (
                item["configuration_path"], item["evidence_type"], item["signal"]
            ),
        )
        for record in self.records:
            if record.detected_language == "JavaScript":
                record.typed_javascript_dialect_evidence = [
                    dict(item) for item in dialect_evidence
                ]
            self._by_relative[record.relative_path] = record
            self._by_name[record.filename.lower()].append(record)

    def __iter__(self) -> Iterator[FileRecord]:
        return iter(self.records)

    def get(self, relative_path: str) -> FileRecord | None:
        return self._by_relative.get(Path(relative_path).as_posix())

    def paths(
        self,
        extensions: set[str] | None = None,
        include_tests: bool = True,
        included_only: bool = False,
    ) -> Iterator[Path]:
        normalized = {value.lower() for value in extensions} if extensions else None
        for record in self.records:
            if normalized is not None and record.extension not in normalized:
                continue
            if not include_tests and record.is_test:
                continue
            if record.exclusion_reason is not None and not (
                include_tests and record.exclusion_reason == "test"
            ):
                continue
            if included_only and not record.included_in_metrics:
                continue
            if record.exclusion_reason in {
                "symlink", "git_symlink", "git_submodule", "unreadable"
            }:
                continue
            yield record._absolute_path

    def records_for_name(self, filename: str) -> tuple[FileRecord, ...]:
        return tuple(self._by_name.get(filename.lower(), ()))

    def read_bytes(self, record_or_path: FileRecord | str | Path) -> bytes | None:
        record = self._coerce_record(record_or_path)
        if record is None:
            return None
        content = self._content_cache.get(record.relative_path)
        if content is not None:
            self.content_cache_reuses += 1
            self.cache_reuses += 1
        return content

    def read_text(
        self,
        record_or_path: FileRecord | str | Path,
        encoding: str | None = None,
    ) -> str | None:
        return self.read_text_with_encoding(record_or_path, encoding)

    def read_text_with_encoding(
        self,
        record_or_path: FileRecord | str | Path,
        encoding: str | None = None,
    ) -> str | None:
        record = self._coerce_record(record_or_path)
        if record is None:
            return None
        data = self.read_bytes(record)
        if data is None:
            return None
        selected = encoding or record.detected_encoding or "utf-8"
        key = (record.relative_path, selected.casefold())
        if key in self._decoded_text_cache:
            self.text_cache_reuses += 1
            self.cache_reuses += 1
            return self._decoded_text_cache[key]
        if record.detected_language == "Python" and record.encoding_error:
            return None
        try:
            text = data.decode(selected)
        except (LookupError, UnicodeDecodeError) as exc:
            if record.detected_language == "Python":
                record.encoding_error = f"{type(exc).__name__}: {exc}"
                return None
            text = data.decode(selected, errors="replace")
        self.decode_operations += 1
        self._decoded_text_cache[key] = text
        return text

    def clear_caches(self) -> None:
        self._content_cache.clear()
        self._decoded_text_cache.clear()

    def record_parser_invocation(self) -> None:
        self.parser_invocations += 1

    def performance_counters(self) -> dict[str, int]:
        return {
            "directories_seen": self.directories_seen,
            "files_seen": self.files_seen,
            "source_candidates": self.source_candidates,
            "file_content_reads": self.file_content_reads,
            "bytes_read": self.bytes_read,
            "files_hashed": self.files_hashed,
            "text_decodes": self.decode_operations,
            "parser_invocations": self.parser_invocations,
            "cache_reuses": self.cache_reuses,
            "content_cache_reuses": self.content_cache_reuses,
            "text_cache_reuses": self.text_cache_reuses,
            "unsupported_files_observed": self.unsupported_files_observed,
            "generated_prefix_reads": self.generated_prefix_reads,
            "git_mode_commands": self.git_mode_command_count,
        }

    def included_source_manifest(self) -> list[dict[str, object]]:
        return [
            {
                "relative_path": record.relative_path,
                "detected_language": record.detected_language,
                "size_bytes": record.size_bytes,
                "content_hash": record.content_hash,
                "read_status": record.read_status,
                "original_encoding": record.original_encoding,
                "parser_encoding": record.parser_encoding,
                "encoding_transformation_applied": record.encoding_transformation_applied,
                "original_byte_length": record.original_byte_length,
                "parser_byte_length": record.parser_byte_length,
                "parser_offsets_map_directly_to_original_bytes": (
                    record.parser_offsets_map_directly_to_original_bytes
                ),
                "nul_count": record.nul_count,
                "nul_density": record.nul_density,
                "nul_positions": record.nul_positions,
                "nul_contexts": record.nul_contexts,
                "alternating_nul_evidence": record.alternating_nul_evidence,
                "suspected_bomless_utf16": record.suspected_bomless_utf16,
                "nul_classification": record.nul_classification,
                "typed_javascript_dialect_evidence": (
                    record.typed_javascript_dialect_evidence
                ),
            }
            for record in self.records
            if record.included_in_metrics
        ]

    def _coerce_record(self, value: FileRecord | str | Path) -> FileRecord | None:
        if isinstance(value, FileRecord):
            return value
        path = Path(value)
        try:
            relative = path.relative_to(self.root).as_posix() if path.is_absolute() else path.as_posix()
        except ValueError:
            return None
        return self._by_relative.get(relative)

    def summary(self) -> dict[str, object]:
        reasons = Counter(
            record.exclusion_reason for record in self.records if record.exclusion_reason
        )
        languages = Counter(
            record.detected_language for record in self.records if record.included_in_metrics
        )
        javascript_family_records = [
            record for record in self.records
            if record.extension in JAVASCRIPT_FAMILY_EXTENSIONS
        ]
        javascript_family_inventory = {
            "contract": "javascript_typescript_family_aggregate",
            "extensions": list(JAVASCRIPT_FAMILY_EXTENSIONS),
            "inventoried_by_extension": dict(
                sorted(Counter(record.extension for record in javascript_family_records).items())
            ),
            "included_by_extension": dict(
                sorted(
                    Counter(
                        record.extension
                        for record in javascript_family_records
                        if record.included_in_metrics
                    ).items()
                )
            ),
            "excluded_by_extension": dict(
                sorted(
                    Counter(
                        record.extension
                        for record in javascript_family_records
                        if not record.included_in_metrics
                    ).items()
                )
            ),
            "scope_status": self.inventory_status,
        }
        return {
            "total_files_discovered": self.files_seen,
            "file_records_created": len(self.records),
            "source_files_included": sum(record.included_in_metrics for record in self.records),
            "files_excluded_by_reason": dict(sorted(reasons.items())),
            "excluded_directories_by_reason": dict(sorted(self.excluded_directories.items())),
            "inventory_status": self.inventory_status,
            "unreadable_directories": len(self.directory_errors),
            "unreadable_files": sum(record.read_status == "failed" for record in self.records),
            "oversized_files": sum(record.read_status == "skipped_oversized" for record in self.records),
            "source_files_oversized": sum(
                bool(record.included_in_metrics and record.oversized)
                for record in self.records
            ),
            "parser_failures": sum(record.parse_status in {"partial", "failed"} for record in self.records),
            "language_distribution": dict(sorted(languages.items())),
            "javascript_family_inventory": javascript_family_inventory,
            "nested_repositories_excluded": sorted(self.nested_repositories),
            "filesystem_walk_count": self.walk_count,
            "pruned_directory_count": len(self.pruned_directories),
            "inventory_mode": "full" if self.full_inventory else "metrics_lightweight",
            "performance_counters": self.performance_counters(),
            "git_mode_map_status": self.git_mode_map_status,
            "git_mode_map_reason": self.git_mode_map_reason,
            "git_mode_map_available": self.git_mode_map_available,
            "git_mode_map_error": self.git_mode_map_error,
            "git_mode_entry_count": self.git_mode_entry_count,
            "git_mode_command_duration_seconds": (
                self.git_mode_command_duration_seconds
            ),
            "git_mode_effective_timeout_seconds": (
                self.git_mode_effective_timeout_seconds
            ),
        }

    def to_dict(self) -> dict[str, object]:
        return {
            "inventory_schema_version": self.config.inventory_schema_version,
            "exclusion_policy_version": self.config.exclusion_policy_version,
            "git_mode_map": {
                "git_mode_map_status": self.git_mode_map_status,
                "git_mode_map_reason": self.git_mode_map_reason,
                "git_mode_map_available": self.git_mode_map_available,
                "git_mode_map_error": self.git_mode_map_error,
                "git_mode_entry_count": self.git_mode_entry_count,
                "command_duration_seconds": self.git_mode_command_duration_seconds,
                "effective_timeout_seconds": self.git_mode_effective_timeout_seconds,
            },
            "summary": self.summary(),
            "directory_errors": list(self.directory_errors),
            "pruned_directories": list(self.pruned_directories),
            "files": [record.to_dict() for record in self.records],
        }
