import tempfile
import unittest
from pathlib import Path

from modules.config import AnalysisConfig
from modules.core_metrics import compute_repository_metrics
from modules.inventory import GENERATED_HEADER_PREFIX_BYTES, RepositoryInventory


class LightweightInventoryPerformanceTests(unittest.TestCase):
    def test_lightweight_inventory_avoids_irrelevant_and_excluded_content(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "src").mkdir()
            (root / "tests").mkdir()
            (root / "node_modules").mkdir()
            (root / "src" / "App.java").write_text(
                "class App { void run(){} }\n", encoding="utf-8"
            )
            (root / "src" / "helper.py").write_text(
                "def helper():\n    return 1\n", encoding="utf-8"
            )
            (root / "tests" / "test_helper.py").write_text(
                "def test_helper(): pass\n", encoding="utf-8"
            )
            (root / "src" / "Generated.java").write_bytes(
                b"// Code generated by fixture. DO NOT EDIT.\n"
                + b"x" * (GENERATED_HEADER_PREFIX_BYTES * 2)
            )
            for index in range(1000):
                (root / "node_modules" / f"dependency_{index}.js").write_text(
                    "class Dependency {}\n", encoding="utf-8"
                )
                (root / f"asset_{index}.png").write_bytes(b"not-an-image")

            config = AnalysisConfig.from_env()
            lightweight = RepositoryInventory(root, config, full_inventory=False)
            metrics = compute_repository_metrics(lightweight)
            counters = lightweight.performance_counters()

            self.assertEqual(metrics["aggregate"]["source_files"], 2)
            self.assertEqual(counters["files_seen"], 1004)
            self.assertEqual(counters["unsupported_files_observed"], 1000)
            self.assertEqual(counters["file_content_reads"], 3)
            self.assertEqual(counters["files_hashed"], 2)
            self.assertEqual(counters["parser_invocations"], 2)
            self.assertLessEqual(counters["files_hashed"], counters["file_content_reads"])
            self.assertLessEqual(
                metrics["aggregate"]["source_files_readable"],
                metrics["aggregate"]["source_files"],
            )
            self.assertLessEqual(
                metrics["aggregate"]["source_files_loc_analyzed"],
                metrics["aggregate"]["source_files_readable"],
            )
            self.assertLessEqual(
                metrics["aggregate"]["source_files_entity_parsed"],
                metrics["aggregate"]["source_files_readable"],
            )
            self.assertLess(counters["bytes_read"], GENERATED_HEADER_PREFIX_BYTES + 1024)
            self.assertEqual(lightweight.get("tests/test_helper.py").read_status, "not_read_excluded")
            generated = lightweight.get("src/Generated.java")
            self.assertEqual(generated.read_status, "prefix_only_excluded")
            self.assertIsNone(generated.content_hash)
            self.assertEqual(
                sum(record.content_hash is not None for record in lightweight), 2
            )
            self.assertEqual(
                lightweight.summary()["excluded_directories_by_reason"]["dependency"], 1
            )

            full = RepositoryInventory(root, config, full_inventory=True)
            full_metrics = compute_repository_metrics(full)
            self.assertEqual(
                {
                    key: metrics["aggregate"][key]
                    for key in ("lines_of_code", "source_files", "classes_structs", "methods_functions")
                },
                {
                    key: full_metrics["aggregate"][key]
                    for key in ("lines_of_code", "source_files", "classes_structs", "methods_functions")
                },
            )

    def test_lightweight_inventory_honors_python_source_encodings(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "latin.py").write_bytes(
                b"# -*- coding: latin-1 -*-\nname = 'caf\xe9'\n"
            )
            (root / "bom.py").write_bytes(
                b"\xef\xbb\xbfdef bom():\n    return 1\n"
            )

            inventory = RepositoryInventory(root, full_inventory=False)
            metric = compute_repository_metrics(inventory)["by_language"]["python"]

            self.assertEqual(inventory.get("latin.py").detected_encoding, "iso-8859-1")
            self.assertEqual(inventory.get("bom.py").detected_encoding, "utf-8-sig")
            self.assertEqual(metric["source_files"], 2)
            self.assertEqual(metric["lines_of_code"], 3)
            self.assertEqual(metric["loc_status"], "complete")
            self.assertEqual(metric["methods_functions_status"], "complete")

    def test_lightweight_invalid_python_encoding_cookie_is_not_complete(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "bad.py").write_bytes(
                b"# coding: not-a-real-codec\nvalue = 1\n"
            )

            inventory = RepositoryInventory(root, full_inventory=False)
            metric = compute_repository_metrics(inventory)["aggregate"]

            self.assertTrue(inventory.get("bad.py").encoding_error)
            self.assertEqual(metric["source_files"], 1)
            self.assertEqual(metric["source_files_status"], "complete")
            self.assertEqual(metric["loc_status"], "failed")
            self.assertEqual(metric["classes_structs_status"], "failed")

    def test_oversized_generated_header_is_excluded_after_bounded_prefix_read(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "Generated.java").write_bytes(
                b"// Code generated by fixture. DO NOT EDIT.\nclass Generated {}\n"
            )
            config = AnalysisConfig.from_env(max_source_file_size_bytes=16)

            inventory = RepositoryInventory(root, config, full_inventory=False)
            metric = compute_repository_metrics(inventory)["aggregate"]
            record = inventory.get("Generated.java")

            self.assertTrue(record.oversized)
            self.assertTrue(record.is_generated)
            self.assertFalse(record.included_in_metrics)
            self.assertEqual(record.exclusion_reason, "generated")
            self.assertEqual(record.read_status, "prefix_only_excluded")
            self.assertEqual(metric["source_files"], 0)
            self.assertEqual(inventory.generated_prefix_reads, 1)
            self.assertLessEqual(inventory.bytes_read, GENERATED_HEADER_PREFIX_BYTES)


if __name__ == "__main__":
    unittest.main()
