#!/usr/bin/env python3
"""Reconstruct production-source scope without importing ArchLens classifiers."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from collections import Counter
from pathlib import Path, PurePosixPath
from typing import Any


LANGUAGE_BY_SUFFIX = {
    ".java": "Java", ".js": "JavaScript", ".jsx": "JavaScript",
    ".mjs": "JavaScript", ".cjs": "JavaScript", ".ts": "TypeScript",
    ".tsx": "TypeScript", ".mts": "TypeScript", ".cts": "TypeScript",
    ".py": "Python", ".go": "Go",
}
TEST_COMPONENT = re.compile(
    r"^(?:__tests__|tests?|specs?|e2e|fixtures?|functionaltests?|integrationtests?|"
    r"integration-tests?|componenttests?|contracttests?|unittests?|testdata)(?:[_-].*)?$",
    re.I,
)
DEPENDENCY_COMPONENTS = {
    "bower_components", "node_modules", "deps", "third-party", "third_party",
}
BUILD_COMPONENTS = {
    ".next", ".nuxt", "bin", "build", "coverage", "dist", "obj", "out", "target",
}
CACHE_COMPONENTS = {
    ".gradle", ".mypy_cache", ".pytest_cache", ".tox", ".venv", "__pycache__", "venv",
}
GENERATED_SUFFIXES = (
    ".gen.go", ".gen.java", ".gen.js", ".gen.jsx", ".gen.ts", ".gen.tsx",
    ".generated.go", ".generated.java", ".generated.js", ".generated.jsx",
    ".generated.ts", ".generated.tsx", ".generated.mjs", ".generated.cjs",
    ".generated.mts", ".generated.cts", ".pb.go", ".pb.gw.go", "_generated.go",
)
BUNDLE_SUFFIXES = (
    ".bundle.js", ".bundle.mjs", ".bundle.cjs", ".bundle.ts", ".bundle.tsx",
    ".bundle.min.js", ".chunk.js", ".chunk.mjs", ".min.js", ".min.mjs",
    ".min.cjs", ".min.ts", ".min.tsx",
)
GENERATED_HEADER = re.compile(
    rb"(?i)(code generated .* do not edit|auto[- ]generated|automatically generated|generated by (?:protoc|swagger|openapi))"
)
KNOWN_VENDOR_JS = re.compile(
    r"^(?:angular(?:-[\w.-]+)?|jquery(?:-[\w.-]+)?|bootstrap|underscore|require)\.js$",
    re.I,
)


def run_git(cache: Path, *args: str, input_bytes: bytes | None = None) -> bytes:
    return subprocess.run(
        ["git", "--git-dir", str(cache), *args], input=input_bytes,
        check=True, capture_output=True,
    ).stdout


def cache_for(cache_root: Path, url: str) -> Path:
    digest = hashlib.sha256(url.lower().encode("utf-8")).hexdigest()[:20]
    return cache_root / f"r_{digest}.git"


def tree_entries(cache: Path, sha: str) -> list[dict[str, Any]]:
    raw = run_git(cache, "ls-tree", "-rlz", sha)
    entries = []
    for item in raw.split(b"\0"):
        if not item:
            continue
        metadata, path = item.split(b"\t", 1)
        mode, kind, object_id, size = metadata.decode("ascii").split()
        entries.append({
            "path": path.decode("utf-8", errors="surrogateescape").replace("\\", "/"),
            "mode": mode,
            "kind": kind,
            "object_id": object_id,
            "size": None if size == "-" else int(size),
        })
    return entries


class BatchReader:
    def __init__(self, cache: Path):
        self.process = subprocess.Popen(
            ["git", "--git-dir", str(cache), "cat-file", "--batch"],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        )

    def read(self, object_id: str) -> bytes:
        assert self.process.stdin is not None and self.process.stdout is not None
        self.process.stdin.write(object_id.encode("ascii") + b"\n")
        self.process.stdin.flush()
        header = self.process.stdout.readline().decode("ascii").strip().split()
        if len(header) != 3 or header[1] != "blob":
            raise RuntimeError(f"unexpected git cat-file response for {object_id}: {header}")
        content = self.process.stdout.read(int(header[2]))
        self.process.stdout.read(1)
        return content

    def close(self) -> None:
        if self.process.stdin:
            self.process.stdin.close()
        self.process.wait(timeout=10)


def test_path(path: PurePosixPath) -> bool:
    components = [part.lower() for part in path.parent.parts]
    name = path.name.lower()
    stem = path.stem.lower()
    return bool(
        any(TEST_COMPONENT.fullmatch(part) for part in components)
        or any(part in {"storagetest", "testsupport", "testutil", "testutils"} for part in components)
        or name in {"conftest.py", "test.py", "tests.py"}
        or re.fullmatch(
            r"(?:cypress|jest|playwright|vitest)\.config\.(?:[cm]?[jt]sx?|mts|cts)|karma\.conf\.(?:[cm]?js|ts)",
            name,
        )
        or name.endswith("_test.go")
        or name.startswith("test_")
        or stem.endswith(("_test", ".test", ".spec", ".unit", ".integration", ".e2e"))
        or path.name.endswith(("Test.java", "Tests.java"))
    )


def classify_path(entry: dict[str, Any]) -> tuple[str | None, str | None, bool]:
    path = PurePosixPath(entry["path"])
    name = path.name.lower()
    parts = [part.lower() for part in path.parent.parts]
    suffix = path.suffix.lower()
    language = LANGUAGE_BY_SUFFIX.get(suffix)
    if name.endswith((".d.ts", ".d.mts", ".d.cts", ".pyi")):
        return language, "declaration_only", False
    if language is None:
        return None, "unsupported_extension", False
    if entry["mode"] == "120000":
        return language, "symlink", False
    if entry["mode"] == "160000" or entry["kind"] == "commit":
        return language, "submodule", False
    if test_path(path):
        return language, "test", False
    if any(part in DEPENDENCY_COMPONENTS for part in parts):
        return language, "dependency", False
    if any(part in BUILD_COMPONENTS for part in parts):
        return language, "build_output", False
    if any(part in CACHE_COMPONENTS for part in parts):
        return language, "cache", False
    if any(part in {"vendor", "vendors"} for part in parts):
        # Domain feature folders named vendors are not automatically third-party.
        if "src" in parts and any(part in {"page", "pages", "model", "models", "api"} for part in parts):
            return language, "ambiguous_vendor_domain", True
        return language, "vendor", False
    if any(part in {"lib", "libs"} for part in parts) and (
        any(part in {"assets", "public", "public-html", "resources", "static", "wwwroot"} for part in parts)
        or KNOWN_VENDOR_JS.fullmatch(name)
    ):
        return language, "vendor_library", False
    if any(name.endswith(value) for value in GENERATED_SUFFIXES) or name.startswith("zz_generated."):
        return language, "generated", False
    if any(part == "generated" or part.startswith("generated-") for part in parts):
        return language, "generated", False
    if "migrations" in parts and suffix == ".py":
        return language, "ambiguous_migration", False
    if any(name.endswith(value) for value in BUNDLE_SUFFIXES):
        return language, "minified_or_bundled", False
    if entry["size"] is not None and entry["size"] > 5 * 1024 * 1024:
        return language, "oversized", False
    return language, None, True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("run_dir", type=Path)
    parser.add_argument("cache_root", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    run_dir = args.run_dir.resolve()
    analysis = json.loads((run_dir / "analysis.json").read_text(encoding="utf-8"))
    reports = []
    for result in analysis:
        url = result["repository_url"]
        sha = result["acquisition"]["analyzed_commit_sha"]
        cache = cache_for(args.cache_root.resolve(), url)
        inventory_path = run_dir / "file_inventory" / f"{result['repository_owner']}__{result['repository_name']}.json"
        production_inventory = json.loads(inventory_path.read_text(encoding="utf-8"))
        production_by_path = {item["relative_path"]: item for item in production_inventory["files"]}
        batch = BatchReader(cache)
        independent = {}
        try:
            for entry in tree_entries(cache, sha):
                language, reason, included = classify_path(entry)
                if language is None:
                    continue
                if included and entry["kind"] == "blob" and (entry["size"] or 0) <= 5 * 1024 * 1024:
                    content = batch.read(entry["object_id"])
                    if GENERATED_HEADER.search(content[:8192]):
                        reason, included = "generated_header", False
                    elif language == "Go" and re.search(
                        rb'(?m)^\s*(?:import\s+)?"testing"\s*$', content[:65536]
                    ):
                        reason, included = "test_helper", False
                    elif "templates" in PurePosixPath(entry["path"]).parent.parts and re.search(
                        rb"(?:\{\{|\{%|<%|\$\{\{)", content
                    ):
                        reason, included = "ambiguous_template_source", False
                    elif language in {"JavaScript", "TypeScript"} and len(content) > 20_000:
                        newlines = max(content.count(b"\n"), 1)
                        if len(content) / newlines > 500:
                            reason, included = "minified_or_bundled", False
                independent[entry["path"]] = {
                    "language": language,
                    "included": included,
                    "reason": reason,
                    "ambiguous": bool(reason and reason.startswith("ambiguous_")),
                    "size_bytes": entry["size"],
                }
        finally:
            batch.close()

        arch_included = {path for path, item in production_by_path.items() if item["included_in_metrics"]}
        independent_included = {path for path, item in independent.items() if item["included"]}
        false_inclusions = sorted(arch_included - independent_included)
        false_exclusions = sorted(independent_included - arch_included)
        classification_disagreements = []
        for path in sorted(set(independent) & set(production_by_path)):
            expected = independent[path]
            actual = production_by_path[path]
            if expected["included"] != actual["included_in_metrics"] or (
                not expected["included"] and expected["reason"] != actual["exclusion_reason"]
            ):
                classification_disagreements.append({
                    "path": path,
                    "independent_included": expected["included"],
                    "independent_reason": expected["reason"],
                    "archlens_included": actual["included_in_metrics"],
                    "archlens_reason": actual["exclusion_reason"],
                    "ambiguous": expected["ambiguous"],
                })
        reports.append({
            "repository_url": url,
            "commit_sha": sha,
            "archlens_included_count": len(arch_included),
            "independent_included_count": len(independent_included),
            "false_inclusion_count": len(false_inclusions),
            "false_inclusions": [
                {"path": path, **independent[path]} for path in false_inclusions
            ],
            "false_exclusion_count": len(false_exclusions),
            "false_exclusions": [
                {"path": path, **independent[path], "archlens_reason": production_by_path.get(path, {}).get("exclusion_reason")}
                for path in false_exclusions
            ],
            "classification_disagreement_count": len(classification_disagreements),
            "classification_disagreements": classification_disagreements,
            "independent_reason_counts": dict(sorted(Counter(item["reason"] or "included" for item in independent.values()).items())),
        })

    payload = {
        "method": "independent git-tree reconstruction; does not import ArchLens inventory code",
        "run_directory": str(run_dir),
        "repositories": reports,
        "totals": {
            "false_inclusions": sum(item["false_inclusion_count"] for item in reports),
            "false_exclusions": sum(item["false_exclusion_count"] for item in reports),
            "classification_disagreements": sum(item["classification_disagreement_count"] for item in reports),
        },
    }
    rendered = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    print(rendered, end="")


if __name__ == "__main__":
    main()
