"""Independent source selection: the Track B reference.

**Independence is the whole point of Track B.** ArchLens's selected file list is
never supplied here. This module walks the tree itself and derives inclusion,
language and classification from its own rules. It imports nothing from
``modules`` — not ``RepositoryInventory``, not the exclusion policy, not the
language map — because a reference that reused any of those would agree by
construction and could never disagree.

**It is not ground truth.** Where it disagrees with ArchLens, either side may be
right, and content-based decisions (generated headers, minification) are ones
this reference deliberately approximates rather than reimplements. Those
disagreements are expected and are classified, not counted as defects.

The rules below were written from observable convention, not from reading
ArchLens's implementation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

#: Extension to language. Independently written; deliberately narrow.
_LANGUAGE_BY_EXTENSION = {
    ".py": "Python",
    ".java": "Java",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".go": "Go",
}

#: Directory names that conventionally hold code that is not the subject's own.
_VENDOR_DIRECTORIES = {
    "vendor", "third_party", "thirdparty", "external", "externals",
}
_DEPENDENCY_DIRECTORIES = {
    "node_modules", "site-packages", ".venv", "venv", "virtualenv",
    ".tox", "bower_components", "eggs", ".eggs",
}
_BUILD_DIRECTORIES = {
    "build", "dist", "out", "target", "bin", "obj", "__pycache__",
    ".gradle", ".mvn", "coverage", ".next", ".nuxt",
}
_TEST_DIRECTORIES = {
    "test", "tests", "testing", "__tests__", "spec", "specs",
}
_VCS_DIRECTORIES = {".git", ".hg", ".svn", ".bzr"}

#: Filename patterns that conventionally mark tests.
_TEST_FILE_SUFFIXES = (
    "_test.py", "_test.go", "_test.java", "_test.js", "_test.ts",
    ".test.js", ".test.ts", ".test.jsx", ".test.tsx",
    ".spec.js", ".spec.ts", ".spec.jsx", ".spec.tsx",
    "test.java", "tests.java",
)
_TEST_FILE_PREFIXES = ("test_",)

#: Filename patterns that conventionally mark minified or bundled output.
_MINIFIED_SUFFIXES = (".min.js", ".min.ts", ".bundle.js", ".min.css")

#: TypeScript declaration-only files carry no implementation.
_DECLARATION_SUFFIXES = (".d.ts",)

#: Markers that conventionally appear in the first lines of generated code.
_GENERATED_MARKERS = (
    "code generated by", "do not edit", "auto-generated", "autogenerated",
    "generated by the protocol buffer compiler", "@generated",
)
_GENERATED_SCAN_BYTES = 2048


@dataclass
class SelectedFile:
    relative_path: str
    language: str | None
    included: bool
    exclusion_reason: str | None
    classifications: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "relative_path": self.relative_path,
            "language": self.language,
            "included": self.included,
            "exclusion_reason": self.exclusion_reason,
            "classifications": sorted(self.classifications),
        }


#: Line prefixes that make a line a comment in any supported language. A
#: generated-code banner is a comment by convention; requiring that is what
#: stops the scan matching source code that merely *mentions* the phrase.
_COMMENT_PREFIXES = ("#", "//", "/*", "*", "<!--")


def _is_generated(path: Path) -> bool:
    """Conventional generated-code banner detection over the file's head.

    The marker must appear **in a comment line**. An earlier version searched
    the raw head text and classified `modules/inventory.py` as generated,
    because ArchLens's own generated-marker regex contains the string
    "do not edit" in ordinary source. Track B caught that as a
    `source_selection_mismatch`; adjudication found the defect was the
    reference's, not ArchLens's. Recorded here so the fix keeps its reason.
    """
    try:
        with path.open("rb") as handle:
            head = handle.read(_GENERATED_SCAN_BYTES)
    except OSError:
        return False
    text = head.decode("utf-8", errors="ignore")
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line.startswith(_COMMENT_PREFIXES):
            continue
        lowered = line.lower()
        if any(marker in lowered for marker in _GENERATED_MARKERS):
            return True
    return False


def select(root: Path) -> list[SelectedFile]:
    """Independently derive the measurable source set beneath ``root``."""
    root = Path(root).resolve()
    found: list[SelectedFile] = []

    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        parts = [part.lower() for part in relative.parts]

        if any(part in _VCS_DIRECTORIES for part in parts):
            continue

        if path.is_symlink():
            found.append(SelectedFile(
                relative.as_posix(), None, False, "symlink", ["symlink"]
            ))
            continue
        if not path.is_file():
            continue

        name = relative.name.lower()
        extension = relative.suffix.lower()
        language = _LANGUAGE_BY_EXTENSION.get(extension)
        classifications: list[str] = []

        directory_parts = parts[:-1]
        reason: str | None = None

        if any(part in _DEPENDENCY_DIRECTORIES for part in directory_parts):
            reason, tag = "dependency", "dependency"
        elif any(part in _VENDOR_DIRECTORIES for part in directory_parts):
            reason, tag = "vendor", "vendor"
        elif any(part in _BUILD_DIRECTORIES for part in directory_parts):
            reason, tag = "build_output", "build_output"
        elif name.endswith(_DECLARATION_SUFFIXES):
            reason, tag = "declaration_only", "declaration_only"
        elif name.endswith(_MINIFIED_SUFFIXES):
            reason, tag = "minified_or_bundled", "minified_or_bundled"
        elif (
            any(part in _TEST_DIRECTORIES for part in directory_parts)
            or name.endswith(_TEST_FILE_SUFFIXES)
            or name.startswith(_TEST_FILE_PREFIXES)
        ):
            reason, tag = "test", "test"
        else:
            tag = None

        if tag:
            classifications.append(tag)

        if reason is None and language is not None and _is_generated(path):
            reason = "generated"
            classifications.append("generated")

        if language is None:
            found.append(SelectedFile(
                relative.as_posix(), None, False,
                reason or "not_a_supported_source_extension", classifications,
            ))
            continue

        found.append(SelectedFile(
            relative.as_posix(), language, reason is None, reason, classifications
        ))
    return found


def included_paths(selection: Iterable[SelectedFile]) -> set[str]:
    return {item.relative_path for item in selection if item.included}


def language_of(selection: Iterable[SelectedFile]) -> dict[str, str | None]:
    return {item.relative_path: item.language for item in selection}
